# -*- coding: utf-8 -*-
"""transkript.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2VpTBkYqZpaR_ADux_QbzFe7GrVEVCZ

Kurulum Kısmı
"""

!pip install assemblyai;

"""Lütfen mp3 mp4 veya wav yükleyin. daha sonra çalıştırdığınzda çıktısı verir. api key olmadan çalışmaz. Sesi metne çevirme kısmı"""

import assemblyai as aai

aai.settings.api_key = "YOUR_KEY_HERE"

audio_url = "dosyaadi.mp3"

transcriber = aai.Transcriber()

transcript = transcriber.transcribe(audio_url)

print(transcript.text)

print(transcript.words)

konu = transcript.get_sentences()
for yazdir in konu:
  print(yazdir)

paragraf = transcript.get_paragraphs()
for psaydir in paragraf:
  print(psaydir.text)

"""Özetleme çalışması"""

import assemblyai as aai

aai.settings.api_key = "YOUR_KEY_HERE"

audio_url = "dosyaadi.mp3"

config = aai.TranscriptionConfig(
  summarization=True,
  summary_model=aai.SummarizationModel.informative,
  summary_type=aai.SummarizationType.bullets
)

transcript = aai.Transcriber().transcribe(audio_url, config)

print(transcript.summary)

"""Detaylı bilgi için : https://www.assemblyai.com/docs/audio-intelligence/sentiment-analysis   elimden geldiği kadarıyla örnek gösterdim. şuan 50$ a kadar ücretsiz bakiye veriyor. tavsiye ederim."""

